/**
 * Connectors a generated app can use (Lovable's "Conectores").
 * - public: values designed to ship in frontend code (publishable keys, site
 *   keys, DSNs). They are written to src/lib/connectors.js.
 * - secret: server-only keys. They never enter the app code; the app calls a
 *   Supabase Edge Function that reads them from the function's secrets.
 */
export type ConnectorKind = 'public' | 'secret';
export interface ConnectorField {key: string; label: string; env: string; placeholder?: string}
export interface Connector {id: string; name: string; category: string; kind: ConnectorKind; description: string; keysUrl: string; baseURL: string; fields: ConnectorField[]; usage: string}

const f = (key: string, label: string, env: string, placeholder?: string): ConnectorField => ({key, label, env, ...(placeholder ? {placeholder} : {})});

export const CONNECTORS: Connector[] = [
  // Pagamentos
  {id: 'stripe', name: 'Stripe', category: 'Pagamentos', kind: 'secret', description: 'Cobranças, assinaturas e checkout.', keysUrl: 'https://dashboard.stripe.com/apikeys', baseURL: 'https://api.stripe.com', fields: [f('secretKey', 'Secret key', 'STRIPE_SECRET_KEY', 'sk_live_… ou sk_test_…')], usage: 'Create Checkout Sessions in an Edge Function (POST https://api.stripe.com/v1/checkout/sessions, form-encoded, Authorization: Bearer STRIPE_SECRET_KEY) and redirect the browser to session.url.'},
  {id: 'stripe-public', name: 'Stripe (chave pública)', category: 'Pagamentos', kind: 'public', description: 'Chave publicável e links de pagamento no site.', keysUrl: 'https://dashboard.stripe.com/apikeys', baseURL: 'https://api.stripe.com', fields: [f('publishableKey', 'Publishable key', 'STRIPE_PUBLISHABLE_KEY', 'pk_…'), f('paymentLink', 'Payment Link (opcional)', 'STRIPE_PAYMENT_LINK', 'https://buy.stripe.com/…')], usage: 'For simple sales, link buttons to connectors.stripePublic.paymentLink.'},
  {id: 'mercadopago', name: 'Mercado Pago', category: 'Pagamentos', kind: 'secret', description: 'Pix, cartão e boleto no Brasil.', keysUrl: 'https://www.mercadopago.com.br/developers/panel/app', baseURL: 'https://api.mercadopago.com', fields: [f('accessToken', 'Access token', 'MERCADOPAGO_ACCESS_TOKEN')], usage: 'Create a checkout preference in an Edge Function (POST https://api.mercadopago.com/checkout/preferences, Authorization: Bearer MERCADOPAGO_ACCESS_TOKEN) and open init_point.'},
  {id: 'mercadopago-public', name: 'Mercado Pago (chave pública)', category: 'Pagamentos', kind: 'public', description: 'Public key para o Checkout Bricks.', keysUrl: 'https://www.mercadopago.com.br/developers/panel/app', baseURL: 'https://api.mercadopago.com', fields: [f('publicKey', 'Public key', 'MERCADOPAGO_PUBLIC_KEY', 'APP_USR-…')], usage: 'Use connectors.mercadopagoPublic.publicKey with the Mercado Pago JS SDK loaded from https://sdk.mercadopago.com/js/v2.'},
  {id: 'paypal', name: 'PayPal', category: 'Pagamentos', kind: 'public', description: 'Botões de pagamento PayPal.', keysUrl: 'https://developer.paypal.com/dashboard/applications', baseURL: 'https://api-m.paypal.com', fields: [f('clientId', 'Client ID', 'PAYPAL_CLIENT_ID')], usage: 'Load https://www.paypal.com/sdk/js?client-id=<clientId>&currency=BRL and render paypal.Buttons.'},
  {id: 'asaas', name: 'Asaas', category: 'Pagamentos', kind: 'secret', description: 'Cobranças recorrentes, Pix e boleto.', keysUrl: 'https://www.asaas.com/customerApiAccessToken/index', baseURL: 'https://api.asaas.com', fields: [f('apiKey', 'API key', 'ASAAS_API_KEY')], usage: 'Call https://api.asaas.com/v3 from an Edge Function with header access_token: ASAAS_API_KEY.'},
  {id: 'lemonsqueezy', name: 'Lemon Squeezy', category: 'Pagamentos', kind: 'secret', description: 'Venda de produtos digitais e assinaturas.', keysUrl: 'https://app.lemonsqueezy.com/settings/api', baseURL: 'https://api.lemonsqueezy.com', fields: [f('apiKey', 'API key', 'LEMONSQUEEZY_API_KEY')], usage: 'Create checkouts in an Edge Function via POST https://api.lemonsqueezy.com/v1/checkouts (Bearer LEMONSQUEEZY_API_KEY).'},
  // E-mail e mensagens
  {id: 'resend', name: 'Resend', category: 'E-mail e mensagens', kind: 'secret', description: 'E-mails transacionais.', keysUrl: 'https://resend.com/api-keys', baseURL: 'https://api.resend.com', fields: [f('apiKey', 'API key', 'RESEND_API_KEY', 're_…')], usage: 'Send email from an Edge Function: POST https://api.resend.com/emails with Bearer RESEND_API_KEY and {from,to,subject,html}.'},
  {id: 'sendgrid', name: 'SendGrid', category: 'E-mail e mensagens', kind: 'secret', description: 'E-mail em escala.', keysUrl: 'https://app.sendgrid.com/settings/api_keys', baseURL: 'https://api.sendgrid.com', fields: [f('apiKey', 'API key', 'SENDGRID_API_KEY', 'SG.…')], usage: 'POST https://api.sendgrid.com/v3/mail/send from an Edge Function (Bearer SENDGRID_API_KEY).'},
  {id: 'brevo', name: 'Brevo', category: 'E-mail e mensagens', kind: 'secret', description: 'E-mail marketing e transacional.', keysUrl: 'https://app.brevo.com/settings/keys/api', baseURL: 'https://api.brevo.com', fields: [f('apiKey', 'API key', 'BREVO_API_KEY')], usage: 'POST https://api.brevo.com/v3/smtp/email from an Edge Function with header api-key: BREVO_API_KEY.'},
  {id: 'mailchimp', name: 'Mailchimp', category: 'E-mail e mensagens', kind: 'secret', description: 'Listas e newsletters.', keysUrl: 'https://us1.admin.mailchimp.com/account/api/', baseURL: 'https://login.mailchimp.com', fields: [f('apiKey', 'API key', 'MAILCHIMP_API_KEY'), f('audienceId', 'Audience ID', 'MAILCHIMP_AUDIENCE_ID')], usage: 'Add subscribers from an Edge Function: POST https://<dc>.api.mailchimp.com/3.0/lists/MAILCHIMP_AUDIENCE_ID/members (dc = suffix of the key).'},
  {id: 'twilio', name: 'Twilio', category: 'E-mail e mensagens', kind: 'secret', description: 'SMS, WhatsApp e voz.', keysUrl: 'https://console.twilio.com', baseURL: 'https://api.twilio.com', fields: [f('accountSid', 'Account SID', 'TWILIO_ACCOUNT_SID', 'AC…'), f('authToken', 'Auth token', 'TWILIO_AUTH_TOKEN'), f('from', 'Número remetente', 'TWILIO_FROM', '+55…')], usage: 'Send SMS/WhatsApp from an Edge Function: POST https://api.twilio.com/2010-04-01/Accounts/<SID>/Messages.json with Basic auth SID:TOKEN.'},
  {id: 'zapi', name: 'Z-API (WhatsApp)', category: 'E-mail e mensagens', kind: 'secret', description: 'Mensagens de WhatsApp.', keysUrl: 'https://app.z-api.io', baseURL: 'https://api.z-api.io', fields: [f('instance', 'Instance ID', 'ZAPI_INSTANCE'), f('token', 'Token', 'ZAPI_TOKEN'), f('clientToken', 'Client-Token', 'ZAPI_CLIENT_TOKEN')], usage: 'POST https://api.z-api.io/instances/<instance>/token/<token>/send-text from an Edge Function with header Client-Token.'},
  {id: 'emailjs', name: 'EmailJS', category: 'E-mail e mensagens', kind: 'public', description: 'Formulário de contato sem servidor.', keysUrl: 'https://dashboard.emailjs.com/admin/account', baseURL: 'https://api.emailjs.com', fields: [f('publicKey', 'Public key', 'EMAILJS_PUBLIC_KEY'), f('serviceId', 'Service ID', 'EMAILJS_SERVICE_ID'), f('templateId', 'Template ID', 'EMAILJS_TEMPLATE_ID')], usage: 'POST https://api.emailjs.com/api/v1.0/email/send with {service_id, template_id, user_id: publicKey, template_params}.'},
  {id: 'formspree', name: 'Formspree', category: 'E-mail e mensagens', kind: 'public', description: 'Recebe formulários por e-mail.', keysUrl: 'https://formspree.io/forms', baseURL: 'https://formspree.io', fields: [f('endpoint', 'Endpoint do formulário', 'FORMSPREE_ENDPOINT', 'https://formspree.io/f/…')], usage: 'POST the form as JSON to connectors.formspree.endpoint with Accept: application/json.'},
  {id: 'web3forms', name: 'Web3Forms', category: 'E-mail e mensagens', kind: 'public', description: 'Formulários grátis sem backend.', keysUrl: 'https://web3forms.com', baseURL: 'https://api.web3forms.com', fields: [f('accessKey', 'Access key', 'WEB3FORMS_ACCESS_KEY')], usage: 'POST to https://api.web3forms.com/submit including access_key.'},
  // IA
  {id: 'openai', name: 'OpenAI', category: 'Inteligência artificial', kind: 'secret', description: 'Chat, imagens e voz no seu app.', keysUrl: 'https://platform.openai.com/api-keys', baseURL: 'https://api.openai.com', fields: [f('apiKey', 'API key', 'OPENAI_API_KEY', 'sk-…')], usage: 'Call https://api.openai.com/v1/chat/completions (or /images/generations) only inside an Edge Function with Bearer OPENAI_API_KEY; stream or return the answer to the app.'},
  {id: 'anthropic', name: 'Anthropic (Claude)', category: 'Inteligência artificial', kind: 'secret', description: 'Assistentes com Claude no seu app.', keysUrl: 'https://console.anthropic.com/settings/keys', baseURL: 'https://api.anthropic.com', fields: [f('apiKey', 'API key', 'ANTHROPIC_API_KEY')], usage: 'Call https://api.anthropic.com/v1/messages from an Edge Function with headers x-api-key and anthropic-version: 2023-06-01.'},
  {id: 'gemini', name: 'Google Gemini', category: 'Inteligência artificial', kind: 'secret', description: 'Texto, visão e resumo.', keysUrl: 'https://aistudio.google.com/app/apikey', baseURL: 'https://generativelanguage.googleapis.com', fields: [f('apiKey', 'API key', 'GEMINI_API_KEY')], usage: 'Call https://generativelanguage.googleapis.com/v1beta/models/<model>:generateContent from an Edge Function with header x-goog-api-key.'},
  {id: 'openrouter', name: 'OpenRouter', category: 'Inteligência artificial', kind: 'secret', description: 'Centenas de modelos com uma chave.', keysUrl: 'https://openrouter.ai/keys', baseURL: 'https://openrouter.ai', fields: [f('apiKey', 'API key', 'OPENROUTER_API_KEY')], usage: 'OpenAI-compatible: POST https://openrouter.ai/api/v1/chat/completions from an Edge Function.'},
  {id: 'elevenlabs', name: 'ElevenLabs', category: 'Inteligência artificial', kind: 'secret', description: 'Voz realista (texto para fala).', keysUrl: 'https://elevenlabs.io/app/settings/api-keys', baseURL: 'https://api.elevenlabs.io', fields: [f('apiKey', 'API key', 'ELEVENLABS_API_KEY')], usage: 'POST https://api.elevenlabs.io/v1/text-to-speech/<voice_id> from an Edge Function (header xi-api-key) and return audio/mpeg.'},
  {id: 'replicate', name: 'Replicate', category: 'Inteligência artificial', kind: 'secret', description: 'Modelos de imagem, vídeo e áudio.', keysUrl: 'https://replicate.com/account/api-tokens', baseURL: 'https://api.replicate.com', fields: [f('apiToken', 'API token', 'REPLICATE_API_TOKEN')], usage: 'Create predictions via POST https://api.replicate.com/v1/models/<owner>/<model>/predictions from an Edge Function (Bearer).'},
  {id: 'perplexity', name: 'Perplexity', category: 'Inteligência artificial', kind: 'secret', description: 'Respostas com busca na web.', keysUrl: 'https://www.perplexity.ai/settings/api', baseURL: 'https://api.perplexity.ai', fields: [f('apiKey', 'API key', 'PERPLEXITY_API_KEY')], usage: 'OpenAI-compatible POST https://api.perplexity.ai/chat/completions from an Edge Function.'},
  {id: 'firecrawl', name: 'Firecrawl', category: 'Inteligência artificial', kind: 'secret', description: 'Ler e extrair dados de sites.', keysUrl: 'https://www.firecrawl.dev/app/api-keys', baseURL: 'https://api.firecrawl.dev', fields: [f('apiKey', 'API key', 'FIRECRAWL_API_KEY', 'fc-…')], usage: 'POST https://api.firecrawl.dev/v1/scrape from an Edge Function (Bearer FIRECRAWL_API_KEY).'},
  // Dados e produtividade
  {id: 'airtable', name: 'Airtable', category: 'Dados e produtividade', kind: 'secret', description: 'Planilhas-banco de dados.', keysUrl: 'https://airtable.com/create/tokens', baseURL: 'https://api.airtable.com', fields: [f('token', 'Personal access token', 'AIRTABLE_TOKEN', 'pat…'), f('baseId', 'Base ID', 'AIRTABLE_BASE_ID', 'app…')], usage: 'Read/write records from an Edge Function at https://api.airtable.com/v0/<baseId>/<table> (Bearer).'},
  {id: 'notion', name: 'Notion', category: 'Dados e produtividade', kind: 'secret', description: 'Páginas e bancos do Notion.', keysUrl: 'https://www.notion.so/my-integrations', baseURL: 'https://api.notion.com', fields: [f('token', 'Integration token', 'NOTION_TOKEN', 'ntn_…')], usage: 'Call https://api.notion.com/v1 from an Edge Function with Bearer and Notion-Version: 2022-06-28.'},
  {id: 'google-sheets', name: 'Google Sheets', category: 'Dados e produtividade', kind: 'secret', description: 'Ler e gravar planilhas.', keysUrl: 'https://console.cloud.google.com/apis/credentials', baseURL: 'https://sheets.googleapis.com', fields: [f('apiKey', 'API key (leitura)', 'GOOGLE_SHEETS_API_KEY'), f('spreadsheetId', 'ID da planilha', 'GOOGLE_SHEETS_ID')], usage: 'Read ranges from an Edge Function: GET https://sheets.googleapis.com/v4/spreadsheets/<id>/values/<range>?key=... (writes require a service account).'},
  {id: 'hubspot', name: 'HubSpot', category: 'Dados e produtividade', kind: 'secret', description: 'CRM: contatos e negócios.', keysUrl: 'https://app.hubspot.com/private-apps', baseURL: 'https://api.hubapi.com', fields: [f('token', 'Private app token', 'HUBSPOT_TOKEN', 'pat-…')], usage: 'Create contacts from an Edge Function: POST https://api.hubapi.com/crm/v3/objects/contacts (Bearer).'},
  {id: 'slack', name: 'Slack', category: 'Dados e produtividade', kind: 'secret', description: 'Avisos em canais do Slack.', keysUrl: 'https://api.slack.com/apps', baseURL: 'https://hooks.slack.com', fields: [f('webhookUrl', 'Incoming webhook URL', 'SLACK_WEBHOOK_URL', 'https://hooks.slack.com/services/…')], usage: 'POST {text} to SLACK_WEBHOOK_URL from an Edge Function.'},
  {id: 'discord', name: 'Discord', category: 'Dados e produtividade', kind: 'secret', description: 'Avisos em canais do Discord.', keysUrl: 'https://support.discord.com/hc/articles/228383668', baseURL: 'https://discord.com', fields: [f('webhookUrl', 'Webhook URL', 'DISCORD_WEBHOOK_URL')], usage: 'POST {content} to DISCORD_WEBHOOK_URL from an Edge Function.'},
  {id: 'telegram', name: 'Telegram', category: 'Dados e produtividade', kind: 'secret', description: 'Bots e notificações no Telegram.', keysUrl: 'https://t.me/BotFather', baseURL: 'https://api.telegram.org', fields: [f('botToken', 'Bot token', 'TELEGRAM_BOT_TOKEN'), f('chatId', 'Chat ID', 'TELEGRAM_CHAT_ID')], usage: 'POST https://api.telegram.org/bot<token>/sendMessage from an Edge Function.'},
  {id: 'calendly', name: 'Calendly', category: 'Dados e produtividade', kind: 'public', description: 'Agendamento incorporado.', keysUrl: 'https://calendly.com/event_types/user/me', baseURL: 'https://calendly.com', fields: [f('url', 'Link da agenda', 'CALENDLY_URL', 'https://calendly.com/seu-nome')], usage: 'Embed connectors.calendly.url with the Calendly inline widget (https://assets.calendly.com/assets/external/widget.js).'},
  {id: 'shopify', name: 'Shopify (Storefront)', category: 'Dados e produtividade', kind: 'public', description: 'Produtos da sua loja Shopify.', keysUrl: 'https://help.shopify.com/manual/apps/app-types/custom-apps', baseURL: 'https://shopify.com', fields: [f('domain', 'Domínio da loja', 'SHOPIFY_DOMAIN', 'minhaloja.myshopify.com'), f('storefrontToken', 'Storefront access token (público)', 'SHOPIFY_STOREFRONT_TOKEN')], usage: 'Query products with the Storefront GraphQL API: POST https://<domain>/api/2024-10/graphql.json with X-Shopify-Storefront-Access-Token.'},
  // Mapas, mídia e conteúdo
  {id: 'google-maps', name: 'Google Maps', category: 'Mapas, mídia e conteúdo', kind: 'public', description: 'Mapas e endereços.', keysUrl: 'https://console.cloud.google.com/google/maps-apis/credentials', baseURL: 'https://maps.googleapis.com', fields: [f('browserKey', 'API key (restrita por domínio)', 'GOOGLE_MAPS_API_KEY')], usage: 'Load https://maps.googleapis.com/maps/api/js?key=<connectors.googleMaps.browserKey> or embed https://www.google.com/maps/embed/v1/place?key=...&q=... in an iframe.'},
  {id: 'mapbox', name: 'Mapbox', category: 'Mapas, mídia e conteúdo', kind: 'public', description: 'Mapas personalizados.', keysUrl: 'https://account.mapbox.com/access-tokens', baseURL: 'https://api.mapbox.com', fields: [f('token', 'Public token', 'MAPBOX_TOKEN', 'pk.…')], usage: 'Use mapbox-gl from a CDN with connectors.mapbox.token.'},
  {id: 'unsplash', name: 'Unsplash', category: 'Mapas, mídia e conteúdo', kind: 'secret', description: 'Fotos gratuitas de alta qualidade.', keysUrl: 'https://unsplash.com/oauth/applications', baseURL: 'https://api.unsplash.com', fields: [f('accessKey', 'Access key', 'UNSPLASH_ACCESS_KEY')], usage: 'Search photos from an Edge Function: GET https://api.unsplash.com/search/photos?query=... with Authorization: Client-ID <key>; credit the photographer.'},
  {id: 'pexels', name: 'Pexels', category: 'Mapas, mídia e conteúdo', kind: 'secret', description: 'Fotos e vídeos gratuitos.', keysUrl: 'https://www.pexels.com/api/', baseURL: 'https://api.pexels.com', fields: [f('apiKey', 'API key', 'PEXELS_API_KEY')], usage: 'GET https://api.pexels.com/v1/search?query=... from an Edge Function with Authorization: <key>.'},
  {id: 'cloudinary', name: 'Cloudinary', category: 'Mapas, mídia e conteúdo', kind: 'public', description: 'Upload e otimização de imagens.', keysUrl: 'https://console.cloudinary.com/settings/upload', baseURL: 'https://api.cloudinary.com', fields: [f('cloudName', 'Cloud name', 'CLOUDINARY_CLOUD_NAME'), f('uploadPreset', 'Unsigned upload preset', 'CLOUDINARY_UPLOAD_PRESET')], usage: 'Upload from the browser with an unsigned preset: POST https://api.cloudinary.com/v1_1/<cloudName>/image/upload (FormData file + upload_preset).'},
  {id: 'youtube', name: 'YouTube Data', category: 'Mapas, mídia e conteúdo', kind: 'secret', description: 'Vídeos e canais do YouTube.', keysUrl: 'https://console.cloud.google.com/apis/credentials', baseURL: 'https://www.googleapis.com', fields: [f('apiKey', 'API key', 'YOUTUBE_API_KEY')], usage: 'GET https://www.googleapis.com/youtube/v3/search from an Edge Function; embed videos with https://www.youtube.com/embed/<id>.'},
  {id: 'openweather', name: 'OpenWeather', category: 'Mapas, mídia e conteúdo', kind: 'secret', description: 'Previsão do tempo.', keysUrl: 'https://home.openweathermap.org/api_keys', baseURL: 'https://api.openweathermap.org', fields: [f('apiKey', 'API key', 'OPENWEATHER_API_KEY')], usage: 'GET https://api.openweathermap.org/data/2.5/weather?q=...&units=metric&lang=pt_br&appid=... from an Edge Function.'},
  {id: 'viacep', name: 'ViaCEP', category: 'Mapas, mídia e conteúdo', kind: 'public', description: 'Endereço pelo CEP (sem chave).', keysUrl: 'https://viacep.com.br', baseURL: 'https://viacep.com.br', fields: [], usage: 'GET https://viacep.com.br/ws/<cep>/json/ directly from the browser to fill address fields.'},
  // Análises e monitoramento
  {id: 'google-analytics', name: 'Google Analytics', category: 'Análises e monitoramento', kind: 'public', description: 'Visitas e conversões.', keysUrl: 'https://analytics.google.com', baseURL: 'https://www.googletagmanager.com', fields: [f('measurementId', 'Measurement ID', 'GA_MEASUREMENT_ID', 'G-…')], usage: 'Inject the gtag.js snippet (https://www.googletagmanager.com/gtag/js?id=<id>) once in main.jsx.'},
  {id: 'posthog', name: 'PostHog', category: 'Análises e monitoramento', kind: 'public', description: 'Análise de produto e eventos.', keysUrl: 'https://app.posthog.com/project/settings', baseURL: 'https://us.i.posthog.com', fields: [f('projectKey', 'Project API key', 'POSTHOG_KEY', 'phc_…'), f('host', 'Host', 'POSTHOG_HOST', 'https://us.i.posthog.com')], usage: 'Capture events with POST <host>/capture/ {api_key, event, distinct_id} or the posthog-js snippet.'},
  {id: 'plausible', name: 'Plausible', category: 'Análises e monitoramento', kind: 'public', description: 'Analytics simples e sem cookies.', keysUrl: 'https://plausible.io/sites', baseURL: 'https://plausible.io', fields: [f('domain', 'Domínio do site', 'PLAUSIBLE_DOMAIN')], usage: 'Add <script defer data-domain="<domain>" src="https://plausible.io/js/script.js"></script>.'},
  {id: 'meta-pixel', name: 'Meta Pixel', category: 'Análises e monitoramento', kind: 'public', description: 'Conversões de anúncios Facebook/Instagram.', keysUrl: 'https://business.facebook.com/events_manager', baseURL: 'https://connect.facebook.net', fields: [f('pixelId', 'Pixel ID', 'META_PIXEL_ID')], usage: 'Inject the fbq base code with the pixel id and call fbq("track","PageView").'},
  {id: 'sentry', name: 'Sentry', category: 'Análises e monitoramento', kind: 'public', description: 'Erros do app em produção.', keysUrl: 'https://sentry.io/settings/projects/', baseURL: 'https://sentry.io', fields: [f('dsn', 'DSN', 'SENTRY_DSN', 'https://…@o0.ingest.sentry.io/0')], usage: 'Report window errors to Sentry with the browser loader script configured with the DSN.'},
  // Login e segurança
  {id: 'turnstile', name: 'Cloudflare Turnstile', category: 'Login e segurança', kind: 'public', description: 'Proteção anti-robô em formulários.', keysUrl: 'https://dash.cloudflare.com/?to=/:account/turnstile', baseURL: 'https://challenges.cloudflare.com', fields: [f('siteKey', 'Site key', 'TURNSTILE_SITE_KEY')], usage: 'Render the Turnstile widget (https://challenges.cloudflare.com/turnstile/v0/api.js) and verify the token in an Edge Function with the secret key.'},
  {id: 'hcaptcha', name: 'hCaptcha', category: 'Login e segurança', kind: 'public', description: 'Captcha para formulários.', keysUrl: 'https://dashboard.hcaptcha.com/sites', baseURL: 'https://hcaptcha.com', fields: [f('siteKey', 'Site key', 'HCAPTCHA_SITE_KEY')], usage: 'Load https://js.hcaptcha.com/1/api.js and render with the site key.'},
  {id: 'clerk', name: 'Clerk', category: 'Login e segurança', kind: 'public', description: 'Login pronto (alternativa ao Supabase Auth).', keysUrl: 'https://dashboard.clerk.com', baseURL: 'https://api.clerk.com', fields: [f('publishableKey', 'Publishable key', 'CLERK_PUBLISHABLE_KEY', 'pk_…')], usage: 'Load Clerk JS from its CDN with the publishable key and mount SignIn/UserButton.'},
  {id: 'firebase', name: 'Firebase (web)', category: 'Login e segurança', kind: 'public', description: 'Auth, Firestore e Storage do Firebase.', keysUrl: 'https://console.firebase.google.com', baseURL: 'https://firebase.google.com', fields: [f('webApiKey', 'apiKey', 'FIREBASE_API_KEY'), f('authDomain', 'authDomain', 'FIREBASE_AUTH_DOMAIN'), f('projectId', 'projectId', 'FIREBASE_PROJECT_ID'), f('appId', 'appId', 'FIREBASE_APP_ID')], usage: 'Initialize the Firebase web SDK (from gstatic CDN ES modules) with {apiKey: connectors.firebase.webApiKey, authDomain, projectId, appId} from connectors.firebase; protect data with Security Rules.'},
];

export function connector(id: string): Connector | undefined {
  return CONNECTORS.find(item => item.id === id);
}

/** camelCase key used in the generated src/lib/connectors.js (e.g. stripe-public → stripePublic). */
export function connectorVariable(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_all, char: string) => char.toUpperCase());
}
